version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: daily
  - package-ecosystem: npm
    schedule:
      interval: daily
  - package-ecosystem: bundler
    schedule:
      interval: daily
