---
development:
  adapter: postgresql
  database: code_development
production:
  url: <%= ENV.fetch("DATABASE_URL", "postgres:///code_production") %>
test:
  adapter: postgresql
  database: code_test
