---
development:
  adapter: sqlite3
  database: db/code_development.sqlite3
production:
  adapter: sqlite3
  database: db/code_production.sqlite3
test:
  adapter: sqlite3
  database: db/code_test.sqlite3
