---
development:
  adapter: postgresql
  database: code_development
production:
  adapter: postgresql
  database: code_production
test:
  adapter: postgresql
  database: code_test
  password: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
