---
development:
  gssencmode: disable
  url: <%= ENV.fetch("DATABASE_URL") %>
production:
  gssencmode: disable
  url: <%= ENV.fetch("DATABASE_URL") %>
test:
  gssencmode: disable
  url: <%= ENV.fetch("DATABASE_URL") %>
