---
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
  logs: app logs -f
  shell: app exec --interactive --reuse "bash"
builder:
  arch: arm64
deploy_timeout: 100
env:
  clear:
    RAILS_ENV: production
  secret:
  - BASE_URL
  - HOST
  - HOSTS
  - RAILS_MASTER_KEY
  - DATABASE_URL
image: dorianmariecom/codedorian.com-staging
proxy:
  healthcheck:
    interval: 10
    timeout: 7200
  hosts:
  - staging.code-dorian.com
  - staging.code.dorianmarie.com
  - staging.codedorian.co
  - staging.codedorian.com
  - staging.codedorian.fr
  - staging.codedorian.net
  - staging.codedorian.org
  ssl: true
registry:
  password:
  - KAMAL_REGISTRY_PASSWORD
  username:
  - KAMAL_REGISTRY_USERNAME
servers:
  jobs:
    cmd: bin/rake solid_queue:start
    hosts:
    - 138.201.175.197
  push:
    cmd: bin/rpush start -f
    hosts:
    - 138.201.175.197
  web:
  - 138.201.175.197
service: codedorian-staging
volumes:
- code_storage:/rails/storage
