service: code
image: dorianmariecom/code
healthcheck:
  max_attempts: 20
servers:
  push:
    hosts:
      - 146.190.28.38
    cmd: bin/rpush start -f
  jobs:
    hosts:
      - 146.190.28.38
    cmd: bin/rake solid_queue:start
  web:
    hosts:
      - 146.190.28.38
    labels:
      traefik.http.routers.code.rule: Host(`staging.codedorian.com`)
      traefik.http.routers.code_secure.entrypoints: websecure
      traefik.http.routers.code_secure.rule: Host(`staging.codedorian.com`)
      traefik.http.routers.code_secure.tls.certresolver: letsencrypt
      traefik.http.routers.code_secure.tls: true
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - BASE_URL
    - DATABASE_URL
    - HOST
    - HOSTS
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY
    - REDIS_URL
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "dorian@dorianmarie.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
accessories:
  db:
    image: postgres:16.1
    host: 146.190.28.38
    port: 5432
    env:
      clear:
        POSTGRES_USER: code
        POSTGRES_DB: code_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7
    host: 146.190.28.38
    port: 6379
    cmd: 'redis-server --requirepass <%= File.read(".env.staging")[/REDIS_PASSWORD="(.*)"/, 1] %>'
    directories:
      - data:/data
