---
env:
  secret:
    - BASE_URL
    - HOST
    - HOSTS
    - RAILS_MASTER_KEY
readiness_delay: 20
service: code
image: dorianmariecom/code
servers:
  web:
    - 138.201.175.197
  jobs:
    cmd: bin/rake solid_queue:start
    hosts:
    - 138.201.175.197
  push:
    cmd: bin/rpush start -f
    hosts:
    - 138.201.175.197
proxy:
  ssl: true
  hosts:
    - code-dorian.com
    - code.dorianmarie.com
    - codedorian.co
    - codedorian.com
    - codedorian.fr
    - codedorian.net
    - codedorian.org
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "code_storage:/rails/storage"
builder:
  arch: arm64
