- instance_functions:
    - name: "&"
      type: function
    - name: "^"
      type: function
    - name: bitwise_and
      type: function
    - name: bitwise_or
      type: function
    - name: bitwise_xor
      type: function
    - name: "|"
      type: function
  name: Boolean
  type: class
- name: Class
  type: class
- name: Code
  type: class
- name: Context
  type: class
- class_functions:
    - name: hour
      type: function
    - name: now
      type: function
    - name: today
      type: function
    - name: tomorrow
      type: function
    - name: yesterday
      type: function
  name: Date
  type: class
- instance_functions:
    - name: "%"
      type: function
    - name: "&"
      type: function
    - name: "*"
      type: function
    - name: "**"
      type: function
    - name: "+"
      type: function
    - name: "-"
      type: function
    - name: "/"
      type: function
    - name: "<"
      type: function
    - name: "<<"
      type: function
    - name: "<="
      type: function
    - name: "<=>"
      type: function
    - name: ">"
      type: function
    - name: "^"
      type: function
    - name: abs
      type: function
    - name: bitwise_and
      type: function
    - name: bitwise_or
      type: function
    - name: bitwise_xor
      type: function
    - name: ceil
      type: function
    - name: clone
      type: function
    - name: compare
      type: function
    - name: division
      type: function
    - name: eight?
      type: function
    - name: five?
      type: function
    - name: floor
      type: function
    - name: four?
      type: function
    - name: inferior
      type: function
    - name: inferior_or_equal
      type: function
    - name: left_shift
      type: function
    - name: minus
      type: function
    - name: modulo
      type: function
    - name: multiplication
      type: function
    - name: nine?
      type: function
    - name: one?
      type: function
    - name: plus
      type: function
    - name: power
      type: function
    - name: right_shift
      type: function
    - name: round
      type: function
    - name: seven?
      type: function
    - name: six?
      type: function
    - name: sqrt
      type: function
    - name: superior
      type: function
    - name: superior_or_equal
      type: function
    - name: ten?
      type: function
    - name: three?
      type: function
    - name: to_decimal
      type: function
    - name: to_integer
      type: function
    - name: to_string
      type: function
    - name: truncate
      type: function
    - name: two?
      type: function
    - name: zero?
      type: function
    - name: "|"
      type: function
  name: Decimal
  type: class
- instance_functions:
    - name: "<"
      type: function
    - name: "<="
      type: function
    - name: "<=>"
      type: function
    - name: ">"
      type: function
    - name: ">="
      type: function
    - name: "[]"
      type: function
    - name: any?
      type: function
    - name: at
      type: function
    - name: clear
      type: function
    - name: compact
      type: function
    - name: compact!
      type: function
    - name: compare
      type: function
    - name: delete
      type: function
    - name: delete_if
      type: function
    - name: delete_unless
      type: function
    - name: dig
      type: function
    - name: each
      type: function
    - name: eight?
      type: function
    - name: empty?
      type: function
    - name: except
      type: function
    - name: fetch
      type: function
    - name: fetch_values
      type: function
    - name: filter
      type: function
    - name: filter!
      type: function
    - name: five?
      type: function
    - name: flatten
      type: function
    - name: four?
      type: function
    - name: get
      type: function
    - name: has_key?
      type: function
    - name: has_value?
      type: function
    - name: inferior
      type: function
    - name: inferior_or_equal
      type: function
    - name: invert
      type: function
    - name: keep_if
      type: function
    - name: keep_unless
      type: function
    - name: key
      type: function
    - name: keys
      type: function
    - name: merge
      type: function
    - name: merge!
      type: function
    - name: nine?
      type: function
    - name: one?
      type: function
    - name: select
      type: function
    - name: select!
      type: function
    - name: seven?
      type: function
    - name: six?
      type: function
    - name: size
      type: function
    - name: superior
      type: function
    - name: superior_or_equal
      type: function
    - name: ten?
      type: function
    - name: three?
      type: function
    - name: to_list
      type: function
    - name: transform_values
      type: function
    - name: two?
      type: function
    - name: values
      type: function
    - name: zero?
      type: function
  name: Dictionary
  type: class
- instance_functions:
    - name: ago
      type: function
    - name: from_now
      type: function
  name: Duration
  type: class
- instance_functions:
    - name: call
      type: function
  name: Function
  type: class
- instance_functions:
    - name: escape
      type: function
    - name: link_to
      type: function
  name: Html
  type: class
- name: IdentifierList
  type: class
- instance_functions:
    - name: "%"
      type: function
    - name: "&"
      type: function
    - name: "*"
      type: function
    - name: "**"
      type: function
    - name: "+"
      type: function
    - name: "-"
      type: function
    - name: "/"
      type: function
    - name: "<"
      type: function
    - name: "<<"
      type: function
    - name: "<="
      type: function
    - name: "<=>"
      type: function
    - name: ">"
      type: function
    - name: ">="
      type: function
    - name: ">>"
      type: function
    - name: "^"
      type: function
    - name: abs
      type: function
    - name: bitwise_and
      type: function
    - name: bitwise_or
      type: function
    - name: bitwise_xor
      type: function
    - name: ceil
      type: function
    - name: clone
      type: function
    - name: compare
      type: function
    - name: day
      type: function
    - name: days
      type: function
    - name: decrement
      type: function
    - name: decrement!
      type: function
    - name: division
      type: function
    - name: eight?
      type: function
    - name: even?
      type: function
    - name: five?
      type: function
    - name: floor
      type: function
    - name: four?
      type: function
    - name: hour
      type: function
    - name: hours
      type: function
    - name: increment
      type: function
    - name: increment!
      type: function
    - name: inferior
      type: function
    - name: inferior_or_equal
      type: function
    - name: left_shift
      type: function
    - name: minus
      type: function
    - name: modulo
      type: function
    - name: multiplication
      type: function
    - name: nine?
      type: function
    - name: odd?
      type: function
    - name: one?
      type: function
    - name: plus
      type: function
    - name: power
      type: function
    - name: right_shift
      type: function
    - name: round
      type: function
    - name: self
      type: function
    - name: seven?
      type: function
    - name: six?
      type: function
    - name: sqrt
      type: function
    - name: superior
      type: function
    - name: superior_or_equal
      type: function
    - name: ten?
      type: function
    - name: three?
      type: function
    - name: times
      type: function
    - name: truncate
      type: function
    - name: two?
      type: function
    - name: unary_minus
      type: function
    - name: zero?
      type: function
    - name: "|"
      type: function
    - name: "ร"
      type: function
    - name: "รท"
      type: function
  name: Integer
  type: class
- instance_functions:
    - name: "<<"
      type: function
    - name: any?
      type: function
    - name: append
      type: function
    - name: detect
      type: function
    - name: each
      type: function
    - name: first
      type: function
    - name: flatten
      type: function
    - name: include?
      type: function
    - name: join
      type: function
    - name: last
      type: function
    - name: map
      type: function
    - name: max
      type: function
    - name: max_by
      type: function
    - name: none?
      type: function
    - name: reduce
      type: function
    - name: reverse
      type: function
    - name: select
      type: function
    - name: select!
      type: function
    - name: size
      type: function
    - name: sort
      type: function
    - name: sum
      type: function
    - name: uniq
      type: function
  name: List
  type: class
- class_functions:
    - name: send
      type: function
  name: Mail
  type: class
- class_functions:
    - instance_functions:
        - name: future?
          type: function
        - name: group
          type: function
        - name: id
          type: function
        - name: past?
          type: function
        - name: time
          type: function
        - name: title
          type: function
        - name: url
          type: function
      name: Event
      type: class
    - instance_functions:
        - name: events
          type: function
        - name: name
          type: function
      name: Group
      type: class
  name: Meetup
  type: class
- name: Nothing
  type: class
- class_functions:
    - name: "!"
      type: function
    - name: "!="
      type: function
    - name: "&&"
      type: function
    - name: "+"
      type: function
    - name: ".."
      type: function
    - name: "..."
      type: function
    - name: "=="
      type: function
    - name: "==="
      type: function
    - name: and
      type: function
    - name: as_json
      type: function
    - name: different
      type: function
    - name: equal
      type: function
    - name: exclusive_range
      type: function
    - name: falsy?
      type: function
    - name: inclusive_range
      type: function
    - name: new
      type: function
    - name: not
      type: function
    - name: or
      type: function
    - name: self
      type: function
    - name: strict_equal
      type: function
    - name: to_boolean
      type: function
    - name: to_class
      type: function
    - name: to_date
      type: function
    - name: to_decimal
      type: function
    - name: to_dictionary
      type: function
    - name: to_duration
      type: function
    - name: to_integer
      type: function
    - name: to_json
      type: function
    - name: to_list
      type: function
    - name: to_nothing
      type: function
    - name: to_range
      type: function
    - name: to_string
      type: function
    - name: to_time
      type: function
    - name: truthy?
      type: function
    - name: "|"
      type: function
  instance_functions:
    - name: "!"
      type: function
    - name: "!="
      type: function
    - name: "&&"
      type: function
    - name: "+"
      type: function
    - name: ".."
      type: function
    - name: "..."
      type: function
    - name: "=="
      type: function
    - name: "==="
      type: function
    - name: and
      type: function
    - name: as_json
      type: function
    - name: different
      type: function
    - name: equal
      type: function
    - name: exclusive_range
      type: function
    - name: falsy?
      type: function
    - name: inclusive_range
      type: function
    - name: not
      type: function
    - name: or
      type: function
    - name: self
      type: function
    - name: strict_equal
      type: function
    - name: to_boolean
      type: function
    - name: to_class
      type: function
    - name: to_date
      type: function
    - name: to_decimal
      type: function
    - name: to_dictionary
      type: function
    - name: to_duration
      type: function
    - name: to_integer
      type: function
    - name: to_json
      type: function
    - name: to_list
      type: function
    - name: to_nothing
      type: function
    - name: to_range
      type: function
    - name: to_string
      type: function
    - name: to_time
      type: function
    - name: truthy?
      type: function
    - name: "|"
      type: function
  name: Object
  type: class
- name: Parameter
  type: class
- instance_functions:
    - name: all?
      type: function
    - name: any?
      type: function
    - name: each
      type: function
    - name: first
      type: function
    - name: last
      type: function
    - name: map
      type: function
    - name: select
      type: function
    - name: step
      type: function
    - name: to_list
      type: function
  name: Range
  type: class
- class_functions:
    - name: send
      type: function
  name: Slack
  type: class
- class_functions:
    - name: send
      type: function
  name: Sms
  type: class
- class_functions:
    - name: create!
      type: function
    - name: exist?
      type: function
    - name: exists?
      type: function
  name: Storage
  type: class
- name: String
  type: class
- class_functions:
    - name: Webhook
      type: class
  name: Stripe
  type: class
- instance_functions:
    - name: after?
      type: function
    - name: before?
      type: function
    - name: future?
      type: function
    - name: hour
      type: function
    - name: now
      type: function
    - name: past?
      type: function
    - name: tomorrow
      type: function
    - name: yesterday
      type: function
  name: Time
  type: class
- class_functions:
    - name: raining?
      type: function
  name: Weather
  type: class
- class_functions:
    - instance_functions:
        - name: author
          type: function
        - name: created_at
          type: function
        - name: html
          type: function
        - name: id
          type: function
        - name: retweet
          type: function
        - name: text
          type: function
        - name: url
          type: function
      name: Post
      type: class
    - instance_functions:
        - name: id
          type: function
        - name: name
          type: function
        - name: url
          type: function
        - name: username
          type: function
      name: User
      type: class
    - name: mentions
      type: function
    - name: search
      type: function
    - name: send
      type: function
  name: X
  type: class
- name: break
  type: function
- name: context
  type: function
- name: evaluate
  type: function
- name: next
  type: function
- name: p
  type: function
- name: print
  type: function
- name: puts
  type: function
