---
- title: Mail
  body: class
  children:
    - arguments:
        body:
          default: nothing
          description: body of the email as text
          optional: true
          type: String
        from:
          default: your primary verified smtp account or dorian@codedorian.com
          description: list of emails with or without names to send from
          optional: true
          type: String
        html:
          default: nothing
          description: body of the email as html
          optional: true
          type: String
        reply_to:
          default: nothing
          description: list of emails with or without names to reply to
          optional: true
          type: String
        subject:
          default: nothing
          description: subject of the email
          optional: true
          type: String
        text:
          default: nothing
          description: body of the email as text
          optional: true
          type: String
        to:
          default: your primary verified smtp account or primary verified email address
          description: list of emails with or without names to send to
          optional: true
          type: String
      body: function
      return: nothing
      title: send
      examples:
        - prompt: send an empty email to myself
          input: Mail.send
        - prompt: send an email to dorian
          input: 'Mail.send(to: "dorian@dorianmarie.com", subject: "Hi", body: "How are you?")'
- title: Weather
  body: class
  functions:
    - raining?
- title: Sms
  body: class
  functions:
    - send
- title: Meetup
  body: class
- title: Meetup::Event
  body: class
  functions:
    - id
    - title
    - time
    - group
    - url
    - past?
    - future?
- title: Meetup::Group
  body: class
  functions:
    - events
    - name
- title: X
  body: class
  functions:
    - mentions
    - search
    - send
- title: X::Post
  body: class
  functions:
    - id
    - url
    - text
    - html
    - retweet
    - created_at
    - author
- title: X::User
  body: class
  functions:
    - username
    - id
    - name
    - url
- title: Slack
  body: class
  functions:
    - send
- title: Stripe
  body: class
- title: Stripe::Webhook
  body: class
- title: Storage
  body: class
  functions:
    - exists?
    - exist?
    - create!
- title: String
  body: class
- title: Boolean
  body: class
- title: break
  body: function
- title: next
  body: function
- title: Class
  body: class
- title: Date
  body: class
- title: Decimal
  body: class
- title: Dictionary
  body: class
- title: Duration
  body: class
- title: Function
  body: class
- title: Integer
  body: class
- title: List
  body: class
- title: Nothing
  body: class
- title: context
  body: function
- title: Object
  body: class
- title: Range
  body: class
- title: String
  body: class
- title: Time
  body: class
- title: Context
  body: class
- title: Code
  body: class
- title: Parameter
  body: class
- title: IdentifierList
  body: class
- title: Html
  body: class
- title: evaluate
  body: function
- title: p
  body: function
- title: print
  body: function
- title: puts
  body: function
