---
dispatchers:
- batch_size: 500
  polling_interval: 1
  recurring_tasks:
    schedule_all_job:
      class: ScheduleAllJob
      schedule: every minute
workers:
- polling_interval: 2
  queues: "*"
  threads: 3
