name: Deploy
on:
  push:
    branches:
      - main
jobs:
  brakeman:
    uses: dorianmariecom/code/.github/workflows/brakeman.yml@${{ github.sha }}

  bundler-audit:
    uses: dorianmariecom/code/.github/workflows/bundler-audit.yml@${{ github.sha }}

  importmap-audit:
    uses: dorianmariecom/code/.github/workflows/importmap-audit.yml@${{ github.sha }}

  importmap-outdated:
    uses: dorianmariecom/code/.github/workflows/importmap-outdated.yml@${{ github.sha }}

  rspec:
    uses: dorianmariecom/code/.github/workflows/rspec.yml@${{ github.sha }}

  rubocop:
    uses: dorianmariecom/code/.github/workflows/rubocop.yml@${{ github.sha }}

  yarn-audit:
    uses: dorianmariecom/code/.github/workflows/yarn-audit.yml@${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - brakeman
      - bundler-audit
      - importmap-audit
      - importmap-outdated
      - rspec
      - rubocop
      - yarn-audit
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          password: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - run: gem install kamal
      - run: kamal lock release
      - run: kamal redeploy --skip-push
