name: Importmap Outdated
on:
  push:
  workflow_call:
jobs:
  importmap-outdated:
    name: Importmap Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/importmap outdated
