name: RSpec
on: [push]
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable --ignore-engines
      - run: sudo apt-get -yqq install libpq-dev
      - run: bin/rails db:create db:schema:load
      - run: bin/rails assets:precompile
      - run: bin/rspec
