name: Yarn Audit
on: [push]

jobs:
  yarn-audit:
    name: Yarn Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn audit
